schema_version = 1
id = "N0058"
title = 'Release Summary: v0.5 "Multi-vault & Attachments"'
created = "2026-04-24T17:24:27.832063700+09:00"
updated = "2026-04-24T17:24:33.675773100+09:00"
tags = [
    "release-note",
    "v0.5",
]
links = []
sources = []
status = "draft"
