schema_version = 1
id = "N0046"
title = "Proposal: Single-step Undo Mechanism"
created = "2026-04-22T15:17:02.003996900+09:00"
updated = "2026-04-27T11:05:54.374201300+09:00"
tags = [
    "proposal",
    "undo",
    "workflow",
]
links = []
sources = []
status = "draft"
