schema_version = 1
id = "N0029"
title = "Elendirna: Problem Statement and Positioning"
created = "2026-04-13T08:53:25.837431700Z"
updated = "2026-05-07T11:03:37.634477800+09:00"
tags = [
    "core",
    "philosophy",
]
links = []
sources = []
status = "draft"
