schema_version = 1
id = "N0059"
title = "v0.5 사후강평 - Codex"
created = "2026-04-24T18:15:43.224835600+09:00"
updated = "2026-04-24T18:29:30.183314300+09:00"
tags = [
    "retrospective",
    "v0.5",
    "codex",
]
baseline = "N0052"
links = []
sources = []
status = "draft"
